# Generated by Django 5.0 on 2024-12-04 01:31

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ValueObjects', '0003_alter_country_country_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('com_slug', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('com_name', models.CharField(max_length=200, null=True)),
                ('com_short_name', models.CharField(max_length=100, null=True)),
                ('com_address', models.CharField(max_length=250, null=True)),
                ('phone', models.CharField(max_length=17, null=True)),
                ('legal_form', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public'), ('Corporation', 'Corporation'), ('Limited', 'Limited'), ('Partnership', 'Partnership'), ('Nonprofit ', 'Nonprofit ')], max_length=35, null=True)),
                ('owner_name', models.CharField(max_length=100, null=True)),
                ('tax_office', models.CharField(max_length=100, null=True)),
                ('tax_no', models.IntegerField(null=True)),
                ('soc_in_office', models.CharField(max_length=100, null=True)),
                ('soc_in_no', models.IntegerField(null=True)),
                ('website', models.URLField(null=True)),
                ('updated_at', models.DateTimeField(verbose_name=datetime.datetime(2024, 12, 4, 1, 31, 24, 272416))),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ValueObjects.city')),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ValueObjects.country')),
                ('manager_incharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
