# Generated by Django 5.0 on 2024-12-04 02:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name=datetime.datetime(2024, 12, 4, 2, 36, 18, 320589)),
        ),
    ]
