# Generated by Django 5.0 on 2024-12-11 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_company_updated_at_company_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_type',
            field=models.CharField(choices=[('\tAgriculture and Farming\t', '\tAgriculture and Farming\t'), ('\tAutomotive\t', '\tAutomotive\t'), ('\tConstruction\t', '\tConstruction\t'), ('\tEducation\t', '\tEducation\t'), ('\tFinance\t', '\tFinance\t'), ('\tFood and Beverage\t', '\tFood and Beverage\t'), ('\tHealthcare\t', '\tHealthcare\t'), ('\tInformation Technology\t', '\tInformation Technology\t'), ('\tManufacturing\t', '\tManufacturing\t'), ('\tReal Estate\t', '\tReal Estate\t'), ('\tRetail\t', '\tRetail\t'), ('\tTelecommunications\t', '\tTelecommunications\t'), ('\tTransportation and Logistics\t', '\tTransportation and Logistics\t'), ('\tTravel and Hospitality\t', '\tTravel and Hospitality\t'), ('\tEnergy\t', '\tEnergy\t'), ('\tMedia and Entertainment\t', '\tMedia and Entertainment\t'), ('\tProfessional Services\t', '\tProfessional Services\t'), ('\tMarketing and Advertising\t', '\tMarketing and Advertising\t'), ('\tEnvironmental Services\t', '\tEnvironmental Services\t'), ('\tFitness and Wellness\t', '\tFitness and Wellness\t'), ('\tBeauty and Personal Care\t', '\tBeauty and Personal Care\t'), ('\tFashion and Apparel\t', '\tFashion and Apparel\t'), ('\tHome and Garden\t', '\tHome and Garden\t'), ('\tNonprofit and Social Services\t', '\tNonprofit and Social Services\t'), ('\tLegal Services\t', '\tLegal Services\t'), ('\tHuman Resources and Staffing\t', '\tHuman Resources and Staffing\t'), ('\tEvent Planning and Management\t', '\tEvent Planning and Management\t'), ('\tSports and Recreation\t', '\tSports and Recreation\t'), ('\tTechnology Hardware\t', '\tTechnology Hardware\t'), ('\tBiotechnology and Pharmaceutica\t', '\tBiotechnology and Pharmaceutica\t'), ('\tInsurance\t', '\tInsurance\t'), ('\tInterior Design and Decor\t', '\tInterior Design and Decor\t'), ('\tWaste Management and Recycling\t', '\tWaste Management and Recycling\t'), ('\tPrinting and Publishing\t', '\tPrinting and Publishing\t'), ('\tE-commerce Platforms\t', '\tE-commerce Platforms\t'), ('\tBlockchain and Cryptocurrency\t', '\tBlockchain and Cryptocurrency\t'), ('\tPet Care and Services\t', '\tPet Care and Services\t'), ('\tArt and Culture\t', '\tArt and Culture\t'), ('\tEngineering Services\t', '\tEngineering Services\t'), ('\tRenewable Energy\t', '\tRenewable Energy\t'), ('\tForestry and Logging\t', '\tForestry and Logging\t'), ('\tAerospace\t', '\tAerospace\t'), ('\tMaritime and Shipping\t', '\tMaritime and Shipping\t'), ('\tGovernment Services\t', '\tGovernment Services\t'), ('\tRenovation and Restoration\t', '\tRenovation and Restoration\t'), ('\tAlternative Medicine\t', '\tAlternative Medicine\t'), ('\tMining and Resources\t', '\tMining and Resources\t'), ('\tWelding and Metal Fabrication\t', '\tWelding and Metal Fabrication\t'), ('\tWine and Spirits\t', '\tWine and Spirits\t'), ('\tInvestment and Venture Capital\t', '\tInvestment and Venture Capital\t'), ('\tFitness Technology\t', '\tFitness Technology\t'), ('\tAudio and Sound Production\t', '\tAudio and Sound Production\t'), ('\tLanguage Services\t', '\tLanguage Services\t'), ('\tMarket Research\t', '\tMarket Research\t'), ('\tAquaculture\t', '\tAquaculture\t'), ('\tVirtual Reality and Augmented R\t', '\tVirtual Reality and Augmented R\t'), ('\tSmart Home Technology\t', '\tSmart Home Technology\t'), ('\tRobotics\t', '\tRobotics\t'), ('\tMobile App Development\t', '\tMobile App Development\t'), ('\tSocial Media Management\t', '\tSocial Media Management\t'), ('\tBlockchain\t', '\tBlockchain\t'), ('\tDigital Marketing\t', '\tDigital Marketing\t'), ('\tElderly Care Services\t', '\tElderly Care Services\t'), ('\t3D Printing\t', '\t3D Printing\t'), ('\tCannabis Industry\t', '\tCannabis Industry\t'), ('\tAugmented Reality for Retail\t', '\tAugmented Reality for Retail\t'), ('\tWater Technology\t', '\tWater Technology\t'), ('\tElectric Vehicles\t', '\tElectric Vehicles\t'), ('\tSelf-Improvement and Personal D\t', '\tSelf-Improvement and Personal D\t'), ('\tSubscription-based Meal Kits\t', '\tSubscription-based Meal Kits\t'), ('\tLanguage Learning\t', '\tLanguage Learning\t'), ('\tHome Automation and Smart Devic\t', '\tHome Automation and Smart Devic\t'), ('\tAdventure Tourism\t', '\tAdventure Tourism\t'), ('\tB2B E-commerce Platforms\t', '\tB2B E-commerce Platforms\t'), ('\tCorporate Social Responsibility\t', '\tCorporate Social Responsibility\t'), ('\tCulinary Tourism\t', '\tCulinary Tourism\t'), ('\tCustom Software Development\t', '\tCustom Software Development\t'), ('\tElderly Technology Solutions\t', '\tElderly Technology Solutions\t'), ('\tEmployee Wellness Programs\t', '\tEmployee Wellness Programs\t'), ('\tE-Sports and Gaming\t', '\tE-Sports and Gaming\t'), ('\tEthical and Fair Trade Products\t', '\tEthical and Fair Trade Products\t'), ('\tGreen Building and Architecture\t', '\tGreen Building and Architecture\t'), ('\tHistorical Tourism\t', '\tHistorical Tourism\t'), ('\tInfluencer Management Agencies\t', '\tInfluencer Management Agencies\t'), ('\tMental Health Services\t', '\tMental Health Services\t'), ('\tMobile Payment Solutions\t', '\tMobile Payment Solutions\t'), ('\tPodcasting\t', '\tPodcasting\t'), ('\tRenewable Energy Consulting\t', '\tRenewable Energy Consulting\t'), ('\tRide-Sharing and Carpooling\t', '\tRide-Sharing and Carpooling\t'), ('\tTelemedicine and Virtual Health\t', '\tTelemedicine and Virtual Health\t'), ('\tVirtual Events and Experiences\t', '\tVirtual Events and Experiences\t'), ('\tYouth and Teen Services\t', '\tYouth and Teen Services\t'), ('\tRobotics Process Automation\t', '\tRobotics Process Automation\t'), ('\tGreen Technology\t', '\tGreen Technology\t'), ('\tEducational Toys and Games\t', '\tEducational Toys and Games\t'), ('\tEco-Tourism\t', '\tEco-Tourism\t'), ('\tSustainable Agriculture\t', '\tSustainable Agriculture\t'), ('\tFinancial Technology (FinTech)\t', '\tFinancial Technology (FinTech)\t'), ('\tCollaborative Workspace\t', '\tCollaborative Workspace\t'), ('\tCybersecurity Consulting\t', '\tCybersecurity Consulting\t'), ('\tSustainable Fashion\t', '\tSustainable Fashion\t'), ('\tPersonal Finance Management\t', '\tPersonal Finance Management\t'), ('\tMobile Health Apps\t', '\tMobile Health Apps\t'), ('\tSustainable Packaging\t', '\tSustainable Packaging\t'), ('\tFood Delivery Services\t', '\tFood Delivery Services\t'), ('\tEdutainment\t', '\tEdutainment\t')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='com_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name=datetime.datetime(2024, 12, 11, 21, 25, 32, 636240)),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='soc_in_office',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_office',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(max_length=350, null=True),
        ),
    ]
