# Generated by Django 5.0 on 2024-12-18 21:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValueObjects', '0004_business_type'),
        ('company', '0003_company_business_type_company_com_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name=datetime.datetime(2024, 12, 18, 21, 46, 36, 666466)),
        ),
        migrations.CreateModel(
            name='branch',
            fields=[
                ('branch_id', models.AutoField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('branch_name', models.CharField(max_length=150)),
                ('branch_location', models.CharField(max_length=250)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ValueObjects.city')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
