# Generated by Django 5.0 on 2024-12-18 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_created_at_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name=datetime.datetime(2024, 12, 18, 21, 47, 8, 374105)),
        ),
    ]
