# Generated by Django 5.0 on 2024-12-18 21:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_branch_branch_id_alter_company_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name=datetime.datetime(2024, 12, 18, 21, 48, 45, 252040)),
        ),
        migrations.CreateModel(
            name='dept',
            fields=[
                ('dept_id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('dept_name', models.CharField(max_length=200)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.branch')),
            ],
        ),
    ]
