from django.db import models


    
business_type_category = {

"	Agriculture and Farming	"	:	"	Agriculture and Farming	"	,
"	Automotive	"	:	"	Automotive	"	,
"	Construction	"	:	"	Construction	"	,
"	Education	"	:	"	Education	"	,
"	Finance	"	:	"	Finance	"	,
"	Food and Beverage	"	:	"	Food and Beverage	"	,
"	Healthcare	"	:	"	Healthcare	"	,
"	Information Technology	"	:	"	Information Technology	"	,
"	Manufacturing	"	:	"	Manufacturing	"	,
"	Real Estate	"	:	"	Real Estate	"	,
"	Retail	"	:	"	Retail	"	,
"	Telecommunications	"	:	"	Telecommunications	"	,
"	Transportation and Logistics	"	:	"	Transportation and Logistics	"	,
"	Travel and Hospitality	"	:	"	Travel and Hospitality	"	,
"	Energy	"	:	"	Energy	"	,
"	Media and Entertainment	"	:	"	Media and Entertainment	"	,
"	Professional Services	"	:	"	Professional Services	"	,
"	Marketing and Advertising	"	:	"	Marketing and Advertising	"	,
"	Environmental Services	"	:	"	Environmental Services	"	,
"	Fitness and Wellness	"	:	"	Fitness and Wellness	"	,
"	Beauty and Personal Care	"	:	"	Beauty and Personal Care	"	,
"	Fashion and Apparel	"	:	"	Fashion and Apparel	"	,
"	Home and Garden	"	:	"	Home and Garden	"	,
"	Nonprofit and Social Services	"	:	"	Nonprofit and Social Services	"	,
"	Legal Services	"	:	"	Legal Services	"	,
"	Human Resources and Staffing	"	:	"	Human Resources and Staffing	"	,
"	Event Planning and Management	"	:	"	Event Planning and Management	"	,
"	Sports and Recreation	"	:	"	Sports and Recreation	"	,
"	Technology Hardware	"	:	"	Technology Hardware	"	,
"	Biotechnology and Pharmaceutica	"	:	"	Biotechnology and Pharmaceutica	"	,
"	Insurance	"	:	"	Insurance	"	,
"	Interior Design and Decor	"	:	"	Interior Design and Decor	"	,
"	Waste Management and Recycling	"	:	"	Waste Management and Recycling	"	,
"	Printing and Publishing	"	:	"	Printing and Publishing	"	,
"	E-commerce Platforms	"	:	"	E-commerce Platforms	"	,
"	Blockchain and Cryptocurrency	"	:	"	Blockchain and Cryptocurrency	"	,
"	Pet Care and Services	"	:	"	Pet Care and Services	"	,
"	Art and Culture	"	:	"	Art and Culture	"	,
"	Engineering Services	"	:	"	Engineering Services	"	,
"	Renewable Energy	"	:	"	Renewable Energy	"	,
"	Forestry and Logging	"	:	"	Forestry and Logging	"	,
"	Aerospace	"	:	"	Aerospace	"	,
"	Maritime and Shipping	"	:	"	Maritime and Shipping	"	,
"	Government Services	"	:	"	Government Services	"	,
"	Renovation and Restoration	"	:	"	Renovation and Restoration	"	,
"	Alternative Medicine	"	:	"	Alternative Medicine	"	,
"	Mining and Resources	"	:	"	Mining and Resources	"	,
"	Welding and Metal Fabrication	"	:	"	Welding and Metal Fabrication	"	,
"	Wine and Spirits	"	:	"	Wine and Spirits	"	,
"	Investment and Venture Capital	"	:	"	Investment and Venture Capital	"	,
"	Fitness Technology	"	:	"	Fitness Technology	"	,
"	Audio and Sound Production	"	:	"	Audio and Sound Production	"	,
"	Language Services	"	:	"	Language Services	"	,
"	Market Research	"	:	"	Market Research	"	,
"	Aquaculture	"	:	"	Aquaculture	"	,
"	Virtual Reality and Augmented R	"	:	"	Virtual Reality and Augmented R	"	,
"	Smart Home Technology	"	:	"	Smart Home Technology	"	,
"	Robotics	"	:	"	Robotics	"	,
"	Mobile App Development	"	:	"	Mobile App Development	"	,
"	Social Media Management	"	:	"	Social Media Management	"	,
"	Blockchain	"	:	"	Blockchain	"	,
"	Digital Marketing	"	:	"	Digital Marketing	"	,
"	Elderly Care Services	"	:	"	Elderly Care Services	"	,
"	3D Printing	"	:	"	3D Printing	"	,
"	Cannabis Industry	"	:	"	Cannabis Industry	"	,
"	Augmented Reality for Retail	"	:	"	Augmented Reality for Retail	"	,
"	Water Technology	"	:	"	Water Technology	"	,
"	Electric Vehicles	"	:	"	Electric Vehicles	"	,
"	Self-Improvement and Personal D	"	:	"	Self-Improvement and Personal D	"	,
"	Subscription-based Meal Kits	"	:	"	Subscription-based Meal Kits	"	,
"	Language Learning	"	:	"	Language Learning	"	,
"	Home Automation and Smart Devic	"	:	"	Home Automation and Smart Devic	"	,
"	Adventure Tourism	"	:	"	Adventure Tourism	"	,
"	B2B E-commerce Platforms	"	:	"	B2B E-commerce Platforms	"	,
"	Corporate Social Responsibility	"	:	"	Corporate Social Responsibility	"	,
"	Culinary Tourism	"	:	"	Culinary Tourism	"	,
"	Custom Software Development	"	:	"	Custom Software Development	"	,
"	Elderly Technology Solutions	"	:	"	Elderly Technology Solutions	"	,
"	Employee Wellness Programs	"	:	"	Employee Wellness Programs	"	,
"	E-Sports and Gaming	"	:	"	E-Sports and Gaming	"	,
"	Ethical and Fair Trade Products	"	:	"	Ethical and Fair Trade Products	"	,
"	Green Building and Architecture	"	:	"	Green Building and Architecture	"	,
"	Historical Tourism	"	:	"	Historical Tourism	"	,
"	Influencer Management Agencies	"	:	"	Influencer Management Agencies	"	,
"	Mental Health Services	"	:	"	Mental Health Services	"	,
"	Mobile Payment Solutions	"	:	"	Mobile Payment Solutions	"	,
"	Podcasting	"	:	"	Podcasting	"	,
"	Renewable Energy Consulting	"	:	"	Renewable Energy Consulting	"	,
"	Ride-Sharing and Carpooling	"	:	"	Ride-Sharing and Carpooling	"	,
"	Telemedicine and Virtual Health	"	:	"	Telemedicine and Virtual Health	"	,
"	Virtual Events and Experiences	"	:	"	Virtual Events and Experiences	"	,
"	Youth and Teen Services	"	:	"	Youth and Teen Services	"	,
"	Robotics Process Automation	"	:	"	Robotics Process Automation	"	,
"	Green Technology	"	:	"	Green Technology	"	,
"	Educational Toys and Games	"	:	"	Educational Toys and Games	"	,
"	Eco-Tourism	"	:	"	Eco-Tourism	"	,
"	Sustainable Agriculture	"	:	"	Sustainable Agriculture	"	,
"	Financial Technology (FinTech)	"	:	"	Financial Technology (FinTech)	"	,
"	Collaborative Workspace	"	:	"	Collaborative Workspace	"	,
"	Cybersecurity Consulting	"	:	"	Cybersecurity Consulting	"	,
"	Sustainable Fashion	"	:	"	Sustainable Fashion	"	,
"	Personal Finance Management	"	:	"	Personal Finance Management	"	,
"	Mobile Health Apps	"	:	"	Mobile Health Apps	"	,
"	Sustainable Packaging	"	:	"	Sustainable Packaging	"	,
"	Food Delivery Services	"	:	"	Food Delivery Services	"	,
"	Edutainment	"	:	"	Edutainment	"	,


 }