# Generated by Django 5.0 on 2024-12-04 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(default='Egypt', max_length=100)),
                ('country_code', models.CharField(max_length=4)),
                ('country_phone_code', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_id', models.SmallIntegerField()),
                ('month_name_eng', models.CharField(max_length=10)),
                ('month_name_ar', models.CharField(max_length=10)),
                ('days_in_month', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=75)),
                ('city_code', models.SmallIntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ValueObjects.country')),
            ],
        ),
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=75)),
                ('line2', models.CharField(max_length=75)),
                ('zipcode', models.SmallIntegerField(null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ValueObjects.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ValueObjects.country')),
            ],
        ),
    ]
