# Generated by Django 5.0 on 2024-12-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValueObjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.SmallIntegerField(max_length=4),
        ),
    ]
