# Generated by Django 5.0 on 2024-12-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValueObjects', '0002_alter_country_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_phone_code',
            field=models.IntegerField(),
        ),
    ]
