# Generated by Django 5.0 on 2024-12-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValueObjects', '0003_alter_country_country_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='business_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type_id', models.SmallIntegerField()),
                ('business_type_name', models.CharField(max_length=150)),
                ('business_type_name_ar', models.CharField(max_length=150)),
            ],
        ),
    ]
